name: Build and Test

on: [push, pull_request]

jobs:
    build_test:
        name: Build and Test
        runs-on: ubuntu-latest

        strategy:
            matrix:
                configuration: [Debug, Release]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set .NET SDK version
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "7.0.x"
                  include-prerelease: true

            - name: Build
              run: dotnet build

            - name: Test
              run: dotnet test
              shell: pwsh
